issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fredrir(@114402558)?/nsql(@1269406277)?:environment:release$
claim_pattern:
  repository_id: ^1269406277$
  repository_owner_id: ^114402558$
  runner_environment: ^self-hosted$
  ref: ^refs/tags/v[0-9A-Za-z.+-]+$
  event_name: ^push$
  environment: ^release$
  job_workflow_ref: ^fredrir/infra/\.github/workflows/rust-release\.yml@(d9016b2889c88f1ec99bfe9d7262343a759e4b69|a57b0e15d5ca1c3180fba6a16cedbc7595e90610)$
  job_workflow_sha: ^(d9016b2889c88f1ec99bfe9d7262343a759e4b69|a57b0e15d5ca1c3180fba6a16cedbc7595e90610)$
permissions:
  actions: write
