issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fredrir(@114402558)?/nsql(@1269406277)?:environment:release$
claim_pattern:
  repository_id: ^1269406277$
  repository_owner_id: ^114402558$
  runner_environment: ^self-hosted$
  ref: ^refs/tags/v[0-9A-Za-z.+-]+$
  event_name: ^push$
  environment: ^release$
  job_workflow_ref: ^fredrir/infra/\.github/workflows/rust-release\.yml@(eb764b837d1fd10cb71fde1963500854aaef5d6c|b2c97f0c98c09099d19696089e55f1e95bd6ac1d)$
  job_workflow_sha: ^(eb764b837d1fd10cb71fde1963500854aaef5d6c|b2c97f0c98c09099d19696089e55f1e95bd6ac1d)$
permissions:
  actions: write
