name: Publish packages
on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
  - cron: '23 4 * * *'
permissions:
  contents: read
concurrency:
  group: publish
  cancel-in-progress: false
jobs:
  publish:
    permissions:
      contents: write
      id-token: write
    uses: fredrir/infra/.github/workflows/packages-publish.yml@cbbf64f0b9a383894e8f4c329d64b996260433c0
    secrets: inherit
    with:
      smoke-scope: quick
