name: Publish packages
on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
  - cron: '23 4 * * *'
permissions:
  contents: read
concurrency:
  group: publish
  cancel-in-progress: false
jobs:
  publish:
    permissions:
      contents: write
      id-token: write
    uses: fredrir/infra/.github/workflows/packages-publish.yml@d9016b2889c88f1ec99bfe9d7262343a759e4b69
    secrets: inherit
    with:
      smoke-scope: quick
